name: flutter_gstreamer_player
description: A GStreamer-powered alternative to Flutter's video_player that support Linux, iOS and Android.
version: 0.0.5
homepage: https://github.com/hpdragon1618/flutter_gstreamer_player

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      elinux:
        pluginClass: FlutterGstreamerPlayerPlugin
      linux:
        pluginClass: FlutterGstreamerPlayerPlugin
      android:
        package: com.hpdragon1618.flutter_gstreamer_player
        pluginClass: FlutterGstreamerPlayerPlugin
      ios:
        pluginClass: FlutterGstreamerPlayerPlugin
